server {
  listen 80;
  server_name _;
  location /api/ {
    proxy_pass ${BACKEND_URL};
    proxy_ssl_server_name on;
    proxy_ssl_name $proxy_host;
  }

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }
}