apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-spc
  namespace: backend
spec:
  provider: azure
  secretObjects:
  - secretName: bytebrain-db-connection-string
    type: Opaque
    data:
    - objectName: bytebrain-db-connection-string
      key: connectionString
  - secretName: bytebrain-jwt-secret
    type: Opaque
    data:
    - objectName: bytebrain-jwt-secret
      key: jwt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3098ef0d-7127-4153-9cfa-1351efb39223"
    keyvaultName: "kvdpk01"
    tenantId: "71f2320a-7027-476f-9cf6-62922955b7c7"
    objects: |
      array:
        - |
          objectName: bytebrain-db-connection-string
          objectType: secret
        - |
          objectName: bytebrain-jwt-secret
          objectType: secret
