apiVersion: v1
kind: Service
metadata:
  name: bytebrain-backend
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: bytebrain-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
